sudo: false
language: node_js
node_js:
  - 'node'
  - '8'
  - '6'
env:
  matrix:
    - MONGODB=4.0.0
    - MONGODB=4.1.1
install: npm install
before_script:
  - npm install run-rs -g
  - run-rs -v 4.0.0 --shell
